[package]
name = "aa-service-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "2.8.2"
axum = "0.7.5"
tokio = { version = "1.37.0", features = ["full"] }
tower = "0.4.13"
serde = { version = "1.0.201", features = ["derive"] }
chrono = "0.4.38"
anyhow = "1.0.86"